build:
    environment:
        php: '7.4'
            
    project_setup:
        before:
            - mysql -e "CREATE DATABASE IF NOT EXISTS user"
            
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'

before_commands:
    - "composer install --prefer-source"

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*
